<?php
/**
 * MMBN4 Tilemap Splitter
 * 
 * This script will receive a combined tileset file, previously generated by
 * PixelPet, and split it in two individual tileset files, which is the
 * expected format to be inserted in-game.
 * 
 * The split logic works by trying to detect the split point: the offset of
 * the next tile after the last one belonging to the first tilemap. That should
 * result in the offset of the first tile from the second tileset, which is
 * commonly the split point, based in the original background files.
 * 
 * Usage: php split_tileset.php <combined_tileset> <first_tilemap> <first_splitted_tileset> <second_splitted_tileset>
 * 
 * Arguments:
 * - combined_tileset: Path to the file containing the combined
 *   tilesets, as binary.
 * - first_tilemap: Path to the file containing the first tilemap,
 *   as binary.
 * - first_splitted_tileset: Path to the destination file where the
 *   first tileset will be saved.
 * - second_splitted_tileset: Path to the destination file where the
 *   second tileset will be saved.
 */

require_once 'common.php';

// Reading parameters from the command line.
if ($argc < 4) {
    echo "Usage: php split_tileset.php <combined_tileset> <first_tilemap> <first_splitted_tileset> <second_splitted_tileset>\n";
    exit(1);
}

$combined_tileset = $argv[1];
$first_tilemap = $argv[2];
$first_splitted_tileset = $argv[3];
$second_splitted_tileset = $argv[4];

if (!file_exists($combined_tileset)) {
    echo "Error: Combined tileset file does not exist.\n";
    exit(1);
}
if (!file_exists($first_tilemap)) {
    echo "Error: First tilemap file does not exist.\n";
    exit(1);
}

$combined_tilemap_filesize = filesize($combined_tileset);

$words = [];

$first_tilemap_file = fopen($first_tilemap, "rb");
while (!feof($first_tilemap_file)) {
    $word = readWord($first_tilemap_file, 'hex');
    
    if (empty($word) || $word == "0000") continue;

    $offset = hexdec($word) * 0x40;
    if ($offset > $combined_tilemap_filesize) continue;

    if (!in_array($word, $words)) {
        $words[$offset] = $word;
    }
}

asort($words);
$offset_last_tile = array_key_last($words);
$split_offset = $offset_last_tile + 0x40;
echo 'Split offset: 0x' . dechex($split_offset) . "\n";

$in = fopen($combined_tileset, 'rb');

$f1 = fopen($first_splitted_tileset, 'wb');
$f2 = fopen($second_splitted_tileset, 'wb');
if ($f1 === false || $f2 === false) {
    echo "Error: Couldn't create the splitted tileset files.\n";
    exit(1);
}

// Writing first splitted tileset file.
$data = fread($in, $split_offset);
fwrite($f1, $data);

// Writing second splitted tileset file.
fseek($in, $split_offset, SEEK_SET);
while (!feof($in)) {
    $data = fread($in, 8192);
    if ($data === false) break;
    if (strlen($data) > 0) {
        fwrite($f2, $data);
    }
}

// Closing files.
fclose($in);
fclose($f1);
fclose($f2);

$out1 = basename($first_splitted_tileset);
$out2 = basename($second_splitted_tileset);
$size1 = filesize($first_splitted_tileset);
$size2 = filesize($second_splitted_tileset);
echo "Generated files:\n";
echo " - {$out1} ({$size1} bytes)\n";
echo " - {$out2} ({$size2} bytes)\n";