@size 48

script 0 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"""
	Welcome to Yai's HP.
	This is the Chat
	BBS.
	"""
	keyWait
		any = false
	clearMsg
	"""
	At the generous
	bequest of Miss Yai,
	"""
	keyWait
		any = false
	clearMsg
	"""
	this board is open
	to the general
	public.
	"""
	keyWait
		any = false
	waitHold
}
script 1 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"""
	Yai! Congrats on
	revamping your HP!
	Looks like I'm the
	"""
	keyWait
		any = false
	clearMsg
	"""
	first poster! Say,
	how's that Tornado
	Dryer you bought at
	"""
	keyWait
		any = false
	clearMsg
	"""
	ElecTown? Let's go
	shopping again!
	"""
	keyWait
		any = false
	waitHold
}
script 2 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"""
	Hey Yai! I see you
	put up your own BBS.
	"""
	keyWait
		any = false
	clearMsg
	"""
	Actually,I created
	my own HP for Battle
	info. Come on over
	"""
	keyWait
		any = false
	clearMsg
	"""
	and I'll initiate
	you into the art of
	viruses busting!
	"""
	keyWait
		any = false
	waitHold
}
script 3 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"Thanks for coming,"
	keyWait
		any = false
	clearMsg
	"""
	everyone! I trust
	you all like my
	stylish design.
	"""
	keyWait
		any = false
	clearMsg
	"""
	Thanks for your post
	Mayl! The dryer
	works like a charm!
	"""
	keyWait
		any = false
	clearMsg
	"""
	Thanks for your post
	too,Dex! I visited
	"""
	keyWait
		any = false
	clearMsg
	"""
	your HP. That
	wallpaper definitely
	has to go!
	"""
	keyWait
		any = false
	waitHold
}
script 4 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"""
	Yeeee-haaaaaaawwww!
	Dex's wallpaper may
	be drab,but it's
	"""
	keyWait
		any = false
	clearMsg
	"""
	better than that
	raunchy design he
	had up before!
	"""
	keyWait
		any = false
	waitHold
}
script 5 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"""
	Guts! What are you
	blabbering about?!
	"""
	keyWait
		any = false
	clearMsg
	"""
	My wallpaper
	expresses the spirit
	of manliness!
	"""
	keyWait
		any = false
	waitHold
}
script 6 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"""
	Hello Yai! It was
	lovely seeing you at
	the ball. How is
	"""
	keyWait
		any = false
	clearMsg
	"""
	Glide? Was he hurt
	in the Navi attack?
	Crime seems rampant
	"""
	keyWait
		any = false
	clearMsg
	"""
	on the Net of late.
	Please,do be
	careful.
	"""
	keyWait
		any = false
	waitHold
}
script 7 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"""
	Hi Yai! That Navi
	attack was scary!
	Speaking of scary,
	"""
	keyWait
		any = false
	clearMsg
	"""
	have you heard the
	rumor about ghost
	"""
	keyWait
		any = false
	clearMsg
	"""
	Navis? Apparently
	ghosts of long-
	deleted Navis are
	"""
	keyWait
		any = false
	clearMsg
	"""
	attacking other
	Navis,and Cyber-
	Sutras don't work!
	"""
	keyWait
		any = false
	waitHold
}
script 8 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"""
	Hi Nikaido! Yai's
	friend Dex here! Are
	those ghost stories
	"""
	keyWait
		any = false
	clearMsg
	"""
	true?! Sound kind
	of exciting! I think
	I'll prowl about the
	"""
	keyWait
		any = false
	clearMsg
	"""
	Net and see if I can
	find any!
	"""
	keyWait
		any = false
	waitHold
}
script 9 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"""
	Haaww?! I-I don't
	like g-ghosts…
	But if Dex orders me
	"""
	keyWait
		any = false
	clearMsg
	"""
	to look around the
	Net,I won't back
	"""
	keyWait
		any = false
	clearMsg
	"""
	down! I just hope
	my GutPunch works…
	"""
	keyWait
		any = false
	waitHold
}
script 10 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"""
	Hi Dex! It's
	Nikaido! One rumor
	"""
	keyWait
		any = false
	clearMsg
	"""
	has it that the
	ghosts are illusions
	generated by your
	"""
	keyWait
		any = false
	clearMsg
	"""
	own mind,so you have
	to overcome your own
	fears to beat them.
	"""
	keyWait
		any = false
	waitHold
}
script 11 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"""
	Hi Nikaido! It looks
	like you and Dex are
	"""
	keyWait
		any = false
	clearMsg
	"""
	two of a kind! I've
	heard about the
	"""
	keyWait
		any = false
	clearMsg
	"""
	ghosts too.
	Apparently they
	"""
	keyWait
		any = false
	clearMsg
	"""
	appear at the end of
	corridors and such.
	"""
	keyWait
		any = false
	waitHold
}
script 12 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"""
	Howdy! It looks like
	a world NetBattle
	championship is
	"""
	keyWait
		any = false
	clearMsg
	"""
	going to take place
	in my country,
	Netopia! Woo-hoo!
	"""
	keyWait
		any = false
	waitHold
}
script 13 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"""
	Hee hee! My father's
	sponsoring that
	tournament. Be sure
	"""
	keyWait
		any = false
	clearMsg
	"""
	to watch it everyone
	and raise the
	ratings!
	"""
	keyWait
		any = false
	waitHold
}
script 14 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"""
	That's the contest
	Lan is participating
	in,right? The
	"""
	keyWait
		any = false
	clearMsg
	"""
	contestants are
	staying in a hotel
	in Netopia. Poor
	"""
	keyWait
		any = false
	clearMsg
	"Lan must be lonely…"
	keyWait
		any = false
	clearMsg
	"Good luck,Lan!"
	keyWait
		any = false
	waitHold
}
script 15 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"""
	Lan is the bomb!
	He's the only guy
	GutsMan and I can't
	"""
	keyWait
		any = false
	clearMsg
	"""
	beat! Don't you dare
	lose to anyone but
	us,Lan!
	"""
	keyWait
		any = false
	waitHold
}
script 16 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"BBS01 ID10"
	keyWait
		any = false
	waitHold
}
script 17 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"BBS01 ID11"
	keyWait
		any = false
	waitHold
}
script 18 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"BBS01 ID12"
	keyWait
		any = false
	waitHold
}
script 19 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"BBS01 ID13"
	keyWait
		any = false
	waitHold
}
script 20 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"BBS01 ID14"
	keyWait
		any = false
	waitHold
}
script 21 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"BBS01 ID15"
	keyWait
		any = false
	waitHold
}
script 22 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"BBS01 ID16"
	keyWait
		any = false
	waitHold
}
script 23 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"BBS01 ID17"
	keyWait
		any = false
	waitHold
}
script 24 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"BBS01 ID18"
	keyWait
		any = false
	waitHold
}
script 25 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"BBS01 ID19"
	keyWait
		any = false
	waitHold
}
script 26 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"BBS01 ID1A"
	keyWait
		any = false
	waitHold
}
script 27 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"BBS01 ID1B"
	keyWait
		any = false
	waitHold
}
script 28 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"BBS01 ID1C"
	keyWait
		any = false
	waitHold
}
script 29 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"BBS01 ID1D"
	keyWait
		any = false
	waitHold
}
script 30 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"BBS01 ID1E"
	keyWait
		any = false
	waitHold
}
script 31 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"BBS01 ID1F"
	keyWait
		any = false
	waitHold
}
script 32 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"BBS01 ID20"
	keyWait
		any = false
	waitHold
}
script 33 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"BBS01 ID21"
	keyWait
		any = false
	waitHold
}
script 34 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"BBS01 ID22"
	keyWait
		any = false
	waitHold
}
script 35 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"BBS01 ID23"
	keyWait
		any = false
	waitHold
}
script 36 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"BBS01 ID24"
	keyWait
		any = false
	waitHold
}
script 37 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"BBS01 ID25"
	keyWait
		any = false
	waitHold
}
script 38 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"BBS01 ID26"
	keyWait
		any = false
	waitHold
}
script 39 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"BBS01 ID27"
	keyWait
		any = false
	waitHold
}
script 40 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"BBS01 ID28"
	keyWait
		any = false
	waitHold
}
script 41 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"BBS01 ID29"
	keyWait
		any = false
	waitHold
}
script 42 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"BBS01 ID2A"
	keyWait
		any = false
	waitHold
}
script 43 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"BBS01 ID2B"
	keyWait
		any = false
	waitHold
}
script 44 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"BBS01 ID2C"
	keyWait
		any = false
	waitHold
}
script 45 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"BBS01 ID2D"
	keyWait
		any = false
	waitHold
}
script 46 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"BBS01 ID2E"
	keyWait
		any = false
	waitHold
}
script 47 mmbn4-lc {
	positionText
		left = 32
		top = 68
		arrowDistance = 3
	positionArrow
		left = 202
		top = 108
	"BBS01 ID2F"
	keyWait
		any = false
	waitHold
}
